### ISSUE TITLE
Add support for scrollwheel clicks

### ISSUE THREAD

**Issue by agraven** [myfreeweb/unixbar#12]
Since scroll wheel actions are just a click with another mouse button code, it should be trivial to add a `ScrollUp` and `ScrollDown` to the `MouseButton` enum that translate to the appropriate code in the `MouseButton::to_number` method.

**Comment by myfreeweb** [comment]
Sorry, I'm not actively maintaining this because I don't use i3/sway anymore, as you can see the last commit was in 2017.

But I can merge patches or add you as a collaborator on the repo :)

**Comment by agraven** [comment]
I'd be more than happy to contribute to the project, it's right down my alley and makes my life much easier :)

**Comment by agraven** [comment]
Fixed in [845363d](https://github.com/myfreeweb/unixbar/commit/845363d872791b3c2a2fd90f44ee31c728e4a1e9).
