### ISSUE TITLE
Arbitrary chain of Format objects in Text widget.

### ISSUE THREAD

**Issue by Ploppz** [myfreeweb/unixbar#2]
I'm trying to achieve separation between text similarly to how I did it in my bash script.
![screenshot](http://i.imgur.com/niqwZj4.png)

Each element is separated by two unicode characters. For the left side like in the picture, we have to keep track of the background color when making a new separator. So I made the following struct. 

```
struct Separator {
    bg: &'static str,
}

impl Separator {
    pub fn new(bg: &'static str) -> Separator {
        Separator {
            bg: bg,
        }
    }
    pub fn separate(&mut self, fg: &'static str, bg: &'static str) -> Format {
        let ret = bfmt![
            fg[self.bg] bg[bg] text["⮀⮁"] fg[fg]
        ];
        self.bg = bg;
        ret
    }
}
```
However, there is a problem with the `bfmt!` in `separate()`: According to the `bfmt!` macro, `text[..]` cannot have any succeeding expressions. Hence, the succeeding `fg[..]` is not expected.

Is there any way to achieve this in the current interface?

Would it be a good idea to change the interface to allow arbitrary chains?

To get an idea what end result I have in mind: something like this http://i.imgur.com/lFkWziW.png

**Comment by myfreeweb** [comment]
Of course it's not expected — even though the macro looks deceptively like an array, it's producing wrapped elements like `Color("#abc", Text("something"))`.

I think the problem is that `current_value` returns only one `Format`. Changing it to return a `Vec<Format>` would allow one widget to output multiple things, like differently colored unicode characters. If that solves your problem, I'd happily accept that code :)

**Comment by Ploppz** [comment]
It seems like a linked list, where some elements must be the last element (?).
What about making it an arbitrary linked list? E.g. `Color("#abc", Text("something", Color("#def")))`? Just an idea. At the moment I'm not sure what is the best way but I will think about it.

**Comment by Ploppz** [comment]
Here is one way to achieve it without chaning the interface. `Vec<Format>` wouldn't really help, as I would need the 'Separator' to determine the background of the _following_ object.
```
    let mut sep = Separator::new("#770000", "#000000");

    UnixBar::new(LemonbarFormatter::new())
        .add(Text::new(bfmt![fg[sep.fg] bg[sep.bg] text["Hello "]]))
        .add(Text::new(sep.separate("#ffffff", "#335533")))
        .add(Text::new(bfmt![fg[sep.fg] bg[sep.bg] text["World "]]))
        .add(Text::new(sep.separate("#00ff00", "#677766")))
        .add(Text::new(bfmt![fg[sep.fg] bg[sep.bg] text["Hello "]]))
        .add(Text::new(sep.separate("#000000", "#00000000")))

.........

struct Separator {
    fg: &'static str,
    bg: &'static str,
}

impl Separator {
    pub fn new(fg: &'static str, bg: &'static str) -> Separator {
        Separator {
            fg: fg,
            bg: bg,
        }
    }
    pub fn separate(&mut self, fg: &'static str, bg: &'static str) -> Format {
        let ret = bfmt![
            fg[self.bg] bg[bg] text["⮀⮁ "]
        ];
        self.fg = fg;
        self.bg = bg;
        ret
    }

    pub fn fg(&self) -> &'static str {
        self.fg
    }
    pub fn bg(&self) -> &'static str {
        self.bg
    }
}
```
![screenshot](http://i.imgur.com/UpgkQGk.png)
I think this is ergonomic enough that the interface doesn't need to change.
