### ISSUE TITLE
Bspwm widget: No update on focused+occupied desktops

### ISSUE THREAD

**Issue by Ploppz** [myfreeweb/unixbar#3]
Although `bspc subsribe` gives one line on every desktop change, it seems like the Bspwm widget only updates when switching to a desktop that is _not both focused and occupied_.

For reproduction: https://bpaste.net/show/4c02f2c02933
On line 37, I print out 'focused' and 'occupied'. It never happens that they are both true, and nothing is printed out when switching to a focused+occupied desktop.

**Comment by myfreeweb** [comment]
I haven't used bspwm since they released some version that changed all the things in the configuration for no good reason…
