### ISSUE TITLE
In fmt[], % becomes two %%

### ISSUE THREAD

**Issue by Ploppz** [myfreeweb/unixbar#9]
For example in cpu load:
```
        .add(Delayed::new(
             Duration::from_secs(1),
             || System::new().cpu_load_aggregate().unwrap(),
             move |res| match res {
                 Ok(cpu) => bfmt![bg[sep.bg] fmt["  {:.1}% ", (1.0 - cpu.idle) * 100.0]],

                 Err(_) => bfmt![bg[sep.bg] text["error"]],
             }))

```
It shows two `%` signs.

**Comment by myfreeweb** [comment]
`fmt` literally just calls the [`format!`](https://doc.rust-lang.org/std/fmt/) macro. Which doesn't seem to use `%` in any way… maybe this happens further along the way — in the lemonbar stuff?

**Comment by Ploppz** [comment]
It's probably because of this: https://github.com/myfreeweb/unixbar/blob/master/src/format/lemonbar.rs#L13

Maybe it's from an older version of lemonbar - nowadays I think you just write '%' for '%'.

**Comment by myfreeweb** [comment]
Oh.

```
/// Turn off escaping for e.g. lemonbar-xft
pub fn new_noescape() -> LemonbarFormatter
```
